/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseObjects.MemberDbo;
import Entities.Member;
import Entities.MemberList;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Diogo
 */
public class MemberManagement extends javax.swing.JFrame {

    private MemberDbo members;
    private ArrayList<MemberList> memberList;
    private DefaultListModel listModel = new DefaultListModel();
    private MemberForm memberForm;

    /**
     * Creates new form MemberList
     */
    public MemberManagement(MemberDbo memberDbo) {
        this.members = memberDbo;

        initComponents();
        showAllMembers();
        this.setLocationRelativeTo(null);
    }

    private void showAllMembers() {

        // Load members to list model
        listModel.clear();
        memberList = members.getMemberList();
        Iterator<MemberList> it = memberList.iterator();
        while (it.hasNext()) {
            listModel.addElement(it.next().getMemberNumber());
            //tmpMember = it.next();
        }
        // Select first member (if exists)
        if (members.count() > 0) {
            lstMembers.setSelectedIndex(0);
        }
    }
    
   

    public ArrayList<MemberList> getMemberList() {
        return memberList;
    }

    public javax.swing.JList<String> getMemberJList() {
        return lstMembers;
    }

    public DefaultListModel getListModel() {
        return listModel;
    }

    public int getSectedMemberIndex() {
        return lstMembers.getSelectedIndex();
    }
    
    private Member getSelectedMember(){
        if(lstMembers.getSelectedIndex() < 0){
            return null;
        }
        int selectedMemberIndex = lstMembers.getSelectedIndex();
        MemberList selectedMember = memberList.get(selectedMemberIndex);
        return members.getMember(selectedMember.getId());
    }

    private Member getSelectedMember22() {
            System.out.print(lstMembers.getSelectedValuesList());
        int selectedMemberIndex = lstMembers.getSelectedIndex();
        
        String selected = lstMembers.getSelectedValue();

        if (selectedMemberIndex < 0) {
            return null;
        }
        MemberList selectedMember = memberList.get(selectedMemberIndex);
        System.out.println(selected);
        return members.searchByMemberNumber(Integer.parseInt(selected));


        /*int selectedMemberIndex = lstMembers.getSelectedIndex();
         MemberList selectedMember = memberList.get(selectedMemberIndex);
         return members.getMember(selectedMember.getId());
        
         String selected = lstMembers.getSelectedValue();
         System.out.println(selected);
         return members.searchByMemberNumber(Integer.parseInt(selected));
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMembers = new javax.swing.JList<String>();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSearchMouseReleased(evt);
            }
        });

        jLabel1.setText("Member number");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        btnCreate.setText("Create");
        btnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCreateMouseReleased(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteMouseReleased(evt);
            }
        });

        btnView.setText("View");
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewMouseReleased(evt);
            }
        });

        lstMembers.setModel(listModel);
        lstMembers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMembersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstMembers);

        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseReleased
        Member member = getSelectedMember();

        if (member == null) {
            return;
        }
        memberForm = new MemberForm(this, members);
        memberForm.viewMember(member);
        memberForm.setVisible(true);
    }//GEN-LAST:event_btnViewMouseReleased

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        Member member = getSelectedMember();

        if (member == null) {
            return;
        }
        memberForm = new MemberForm(this, members);
        memberForm.editMember(member);
        memberForm.setVisible(true);
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnCreateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateMouseReleased
        memberForm = new MemberForm(this, members);
        memberForm.createMember();
        memberForm.setVisible(true);
    }//GEN-LAST:event_btnCreateMouseReleased

    private void btnDeleteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseReleased
        Member member = getSelectedMember();

        if (member == null) {
            return;
        }
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the member '" + member.getName() + "'?", "Delete", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            members.removeMember(member.getId());
            memberList.remove(lstMembers.getSelectedIndex());
            listModel.remove(lstMembers.getSelectedIndex());
        }
    }//GEN-LAST:event_btnDeleteMouseReleased

    private void btnSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseReleased
        int memberNumber;

        if (this.txtSearch.getText().isEmpty()) {
            this.txtSearch.setBackground(Color.white);
            showAllMembers();
        } else {
            try {
                memberNumber = Integer.parseInt(this.txtSearch.getText());
                this.txtSearch.setBackground(Color.white);
            } catch (NumberFormatException e) {
                this.txtSearch.setBackground(Color.red);
                return;
            }
            Member searchedMember = members.searchByMemberNumber(memberNumber);
            if (searchedMember == null) {
                JOptionPane.showConfirmDialog(null, "Member not found, displaying all members", "Search", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                showAllMembers();
            } else {
                listModel.clear();
                listModel.addElement(searchedMember.getMemberNumber());
            }
        }
    }//GEN-LAST:event_btnSearchMouseReleased

    private void lstMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMembersMouseClicked
        
        // Double click
        if (evt.getClickCount() == 2) {
            Member member = getSelectedMember();

            if (member == null) {
                return;
            }
            memberForm = new MemberForm(this, members);
            memberForm.viewMember(member);
            memberForm.setVisible(true);
        }
    }//GEN-LAST:event_lstMembersMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMembers;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
