/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DatabaseObjects.TennisClubDboCollection;

/**
 *
 * @author Diogo
 */
public class StartupForm extends javax.swing.JFrame {
    
    // Dbo collection, contains all entities Dbo
    private TennisClubDboCollection dboCollection;
    
    /**
     * Creates new form StartupForm
     */
    public StartupForm(TennisClubDboCollection dboCollection) {
        this.dboCollection = dboCollection;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMembers = new javax.swing.JButton();
        btnTennisCourts = new javax.swing.JButton();
        btnReservations = new javax.swing.JButton();
        btnTennisClub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMembers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/member.png"))); // NOI18N
        btnMembers.setText("Members");
        btnMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMembersMouseReleased(evt);
            }
        });

        btnTennisCourts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tennisCourt.png"))); // NOI18N
        btnTennisCourts.setText("Tennis Courts");
        btnTennisCourts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTennisCourtsMouseReleased(evt);
            }
        });

        btnReservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/reservation.png"))); // NOI18N
        btnReservations.setText("Reservations");
        btnReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnReservationsMouseReleased(evt);
            }
        });

        btnTennisClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/tennisClub.png"))); // NOI18N
        btnTennisClub.setText("Tennis Club");
        btnTennisClub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTennisClubMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTennisCourts, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(btnTennisClub, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReservations, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTennisCourts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTennisClub, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMembersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMembersMouseReleased
        MemberManagement membersManagement = new MemberManagement(dboCollection.getMemberDbo());
        membersManagement.setVisible(true);
    }//GEN-LAST:event_btnMembersMouseReleased

    private void btnTennisCourtsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTennisCourtsMouseReleased
        TennisCourtManagement tennisCourtManagement = new TennisCourtManagement(dboCollection.getTennisCourtsDbo());
        tennisCourtManagement.setVisible(true);
    }//GEN-LAST:event_btnTennisCourtsMouseReleased

    private void btnReservationsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservationsMouseReleased
        ReservationManagement reservationManagement = new ReservationManagement(dboCollection.getReservationsDbo(), dboCollection.getTennisCourtsDbo(), dboCollection.getMemberDbo(), dboCollection.getTennisClubsDbo());
        reservationManagement.setVisible(true);
    }//GEN-LAST:event_btnReservationsMouseReleased

    private void btnTennisClubMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTennisClubMouseReleased
        // TODO add your handling code here:
        TennisClubForm tennisClubForm = new TennisClubForm (dboCollection.getTennisClubsDbo());
        tennisClubForm.editTennisClub();
        tennisClubForm.setVisible(true);
        
    }//GEN-LAST:event_btnTennisClubMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMembers;
    private javax.swing.JButton btnReservations;
    private javax.swing.JButton btnTennisClub;
    private javax.swing.JButton btnTennisCourts;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
